# Generated by Django 4.1 on 2022-09-24 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0004_alter_categoryoffer_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_offer_apply',
            field=models.BooleanField(default=True, max_length=20),
        ),
    ]
