# Generated by Django 4.1 on 2022-09-24 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0005_product_is_offer_apply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryoffer',
            name='status',
            field=models.BooleanField(default=True, max_length=20),
        ),
    ]
