# Generated by Django 4.1 on 2022-09-25 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0006_alter_categoryoffer_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrontBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('banner1', models.ImageField(blank=True, null=True, upload_to='static/images')),
                ('banner2', models.ImageField(blank=True, null=True, upload_to='static/images')),
                ('banner3', models.ImageField(blank=True, null=True, upload_to='static/images')),
            ],
        ),
        migrations.CreateModel(
            name='SubBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('banner1', models.ImageField(blank=True, null=True, upload_to='static/images')),
                ('banner2', models.ImageField(blank=True, null=True, upload_to='static/images')),
                ('banner3', models.ImageField(blank=True, null=True, upload_to='static/images')),
            ],
        ),
    ]
