# Generated by Django 4.1 on 2022-09-25 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0007_frontbanner_subbanner'),
    ]

    operations = [
        migrations.AddField(
            model_name='frontbanner',
            name='select',
            field=models.BooleanField(default=False, max_length=20),
        ),
        migrations.AddField(
            model_name='subbanner',
            name='select',
            field=models.BooleanField(default=False, max_length=20),
        ),
    ]
