# Generated by Django 4.1 on 2022-09-25 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0008_frontbanner_select_subbanner_select'),
    ]

    operations = [
        migrations.AddField(
            model_name='frontbanner',
            name='status',
            field=models.BooleanField(default=False, max_length=20),
        ),
    ]
