# Generated by Django 4.1 on 2022-09-26 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0010_bannerapplied'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subbanner',
            old_name='head',
            new_name='head1',
        ),
        migrations.RenameField(
            model_name='subbanner',
            old_name='description',
            new_name='head2',
        ),
        migrations.AddField(
            model_name='subbanner',
            name='head3',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.CreateModel(
            name='SubBannerApplied',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False, max_length=20)),
                ('subbanner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.subbanner')),
            ],
        ),
    ]
