# Generated by Django 4.1 on 2022-09-27 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0011_rename_head_subbanner_head1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_actual',
            field=models.DecimalField(decimal_places=2, default=True, max_digits=8),
        ),
    ]
