# Generated by Django 4.1 on 2022-09-27 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0012_product_price_actual'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_till', models.DateField()),
                ('Name', models.CharField(max_length=100, unique=True)),
                ('percentage', models.IntegerField()),
                ('description', models.TextField()),
                ('status', models.BooleanField(default=True, max_length=100)),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.product')),
            ],
        ),
    ]
