from django.urls import path
from . import views
urlpatterns = [
    path('', views.homepage_admin,name='dashboard'),
    path('coupon_add', views.coupon_add, name='coupon_add'),
    path('coupon_view', views.coupon, name='coupon_view'),
    path('product_offer',views.product_offer,name='product_offer'),
    path('product_offer_add',views.product_offer_add,name='product_offer_add'),
    path('export_to_excel',views.export_to_excel,name='export_to_excel'),
    path('sales_report_date',views.sales_report_date,name='sales_report_date'),
    # path('sales_report_view',views.sales_report_view,name='sales_report_view'),
    path('category', views.add_cate, name='add_cate'),
    path('offer_add', views.offer_add, name='offer_add'),
    path('offer_view', views.offer_view, name='offer_view'),
    path('main_banner_add', views.main_banner_add, name='main_banner_add'),
    path('banner_view', views.banner_view, name='banner_view'),
    path('export_to_pdf',views.export_to_pdf,name='export_to_pdf'),
    path('cate_view', views.cate_display, name='cate_view'),
    path('usermanage', views.user_manage, name='user_manage'),
    path('productmanage', views.add_product, name='add_pro'),
    path('product_page', views.product_page, name='product'),
    path('order_view', views.order_view_admin, name='order_view_admin'),
    path('admin_login', views.admin_login, name='admin_log'),
    path('admin_logout', views.logout, name='admin_logout'),
    path('sub_banner_view',views.sub_banner_view,name='sub_banner_view'),
    path('sub_banner_add',views.sub_banner_add,name='sub_banner_add'),
    path('<id>', views.user_block, name='user_block'),
    path('update/<id>', views.update_prod, name='update'),
    path('delete/<id>', views.delete_prod, name='del_prod'),
    path('order_detail/<id>', views.order_detail, name='order_detail'),
    path('cancel_order/<id>', views.order_cancel, name='cancel_order'),
    path('cancel_order_product/<id>', views.order_cancel_product, name='cancel_order_product'),
    path('order_product_detail/<id>', views.order_product_detail, name='order_product_detail'),
    path('offer_del/<id>', views.offer_del, name='remove_offer'),
    path('offer_edit/<id>',views.offer_edit,name='offer_edit'),
    path('offer_delete/<id>',views.offer_delete,name='offer_delete'),
    path('coupon_delete/<id>',views.del_coupon,name='coupon_delete'),
    path('product_offer_delete/<id>',views.product_offer_delete,name='product_offer_delete'),
    path('product_offer_cancel/<id>',views.product_offer_cancel,name='product_offer_cancel'),
    path('remove_cate/<id>',views.remove_cate,name='remove_cate'),
    path('main_banner_select/<id>',views.main_banner_select,name='main_banner_select'),
    path('sub_banner_select/<id>',views.sub_banner_select,name='sub_banner_select'),


]
