# Generated by Django 4.1 on 2022-09-25 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0006_alter_categoryoffer_status'),
        ('user_app', '0003_wallet'),
    ]

    operations = [
        migrations.CreateModel(
            name='CouponApplied',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False, max_length=20)),
                ('coupon_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.coupon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.usersignup')),
            ],
        ),
    ]
