# Generated by Django 4.1 on 2022-09-25 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0007_frontbanner_subbanner'),
        ('user_app', '0004_couponapplied'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnedOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('status', models.BooleanField(default=True, max_length=20)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.order')),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.usersignup')),
            ],
        ),
    ]
